-- Real database tests. Synthetic fixtures remain inside a rollback transaction.
begin;
do $$
declare uid uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); l1 uuid; l2 uuid; o1 uuid; o2 uuid; m1 uuid; m2 uuid; cid uuid; contact1 uuid; k uuid:=gen_random_uuid(); received timestamptz:=now(); p uuid; ap uuid; pm uuid;
begin
 insert into auth.users(id,email,email_confirmed_at) values(uid,'silvijn@silvijnstudio.com',now()),(outsider,'core-outsider@example.invalid',now());
 perform set_config('request.jwt.claims',jsonb_build_object('sub',uid,'role','authenticated','email','silvijn@silvijnstudio.com')::text,true);
 insert into public.leads(business_name,industry,city,province,website_status,source,email) values('CORE FIXTURE ONE','test','test','test','no_website','manual','reply@example.invalid') returning id into l1;
 insert into public.leads(business_name,industry,city,province,website_status,source,email) values('CORE FIXTURE TWO','test','test','test','no_website','manual','reply@example.invalid') returning id into l2;
 perform public.transition_lead(l1,'new','analyzing','Owner starts analysis');
 perform public.transition_lead(l1,'analyzing','qualified','Qualification reviewed');
 begin perform public.transition_lead(l1,'new','qualified','Stale update attempt'); raise exception 'TEST: stale transition accepted'; exception when raise_exception then if sqlerrm<>'STALE_LEAD_STATE_REFRESH_REQUIRED' then raise; end if; end;
 begin perform public.transition_lead(l1,'qualified','paid','Skip finance gates'); raise exception 'TEST: invalid edge accepted'; exception when raise_exception then if sqlerrm not like 'INVALID_LEAD_TRANSITION:%' then raise; end if; end;
 begin perform public.transition_lead(l1,'qualified','website_interested','No reply exists'); raise exception 'TEST: interest without reply accepted'; exception when raise_exception then if sqlerrm<>'CONFIRMED_PROSPECT_REPLY_REQUIRED' then raise; end if; end;
 insert into public.outreach_drafts(lead_id,subject,body) values(l1,'draft one','Unsent draft') returning id into o1;
 insert into public.outreach_drafts(lead_id,subject,body,status,sent_at) values(l1,'sent two','Synthetic sent evidence','sent',now()-interval '1 hour') returning id into o2;
 if (select count(*) from public.outreach_drafts where lead_id=l1)<>2 then raise exception 'TEST: multiple outreach missing'; end if;
 if exists(select 1 from public.conversations where lead_id=l1) then raise exception 'TEST: unanswered outreach created conversation'; end if;
 insert into public.inbound_messages(lead_id,sender,body,source) values(l1,'reply@example.invalid','Unverified old/manual record','mock');
 if exists(select 1 from public.conversations where lead_id=l1) then raise exception 'TEST: unverified/mock message created conversation'; end if;
 m1:=public.record_prospect_reply(l1,'email','REPLY@example.invalid','Actual reply recorded manually','Yes, tell me more',received,k,o2);
 select conversation_id,contact_id into cid,contact1 from public.inbound_messages where id=m1;
 if cid is null then raise exception 'TEST: reply did not create conversation'; end if;
 if (select count(*) from public.conversations where lead_id=l1)<>1 then raise exception 'TEST: duplicate conversations'; end if;
 begin insert into public.conversations(lead_id,contact_id,channel,thread_key,first_reply_id,last_reply_at) values(l1,contact1,'email','duplicate-initial-reply',m1,now()); raise exception 'TEST: same initial reply created two conversations'; exception when unique_violation then null; end;
 if (select conversation_id from public.outreach_drafts where id=o2)<>cid then raise exception 'TEST: outreach reply relationship missing'; end if;
 if (select conversation_id from public.outreach_drafts where id=o1) is not null then raise exception 'TEST: unanswered draft autoattached'; end if;
 if public.record_prospect_reply(l1,'email','reply@example.invalid','Actual reply recorded manually','Yes, tell me more',received,k,o2)<>m1 then raise exception 'TEST: idempotent retry duplicated reply'; end if;
 begin perform public.record_prospect_reply(l2,'email','reply@example.invalid','Actual reply recorded manually','Yes, tell me more',received,k); raise exception 'TEST: key crossed leads'; exception when raise_exception then if sqlerrm<>'IDEMPOTENCY_KEY_CONFLICT' then raise; end if; end;
 m2:=public.record_prospect_reply(l1,'email','reply@example.invalid','Second','Second reply',received,gen_random_uuid());
 if (select conversation_id from public.inbound_messages where id=m2)<>cid then raise exception 'TEST: same thread not reused'; end if;
 perform public.record_prospect_reply(l1,'email','other@example.invalid','Other contact','A separate contact reply',received,gen_random_uuid());
 if (select count(*) from public.conversations where lead_id=l1)<>2 then raise exception 'TEST: different contacts merged'; end if;
 begin perform public.record_prospect_reply(l2,'email','reply@example.invalid','Cross lead','Wrong target',received,gen_random_uuid(),o2); raise exception 'TEST: cross-lead reply linked'; exception when foreign_key_violation then null; end;
 begin insert into public.sales_interactions(lead_id,inbound_message_id) values(l2,m1); raise exception 'TEST: cross-lead analysis linked'; exception when foreign_key_violation then null; end;
 begin update public.inbound_messages set lead_id=l2 where id=m1; raise exception 'TEST: message identity changed'; exception when raise_exception then if sqlerrm<>'MESSAGE_IDENTITY_IMMUTABLE' then raise; end if; end;
 begin insert into public.inbound_messages(lead_id,conversation_id,body) values(l2,cid,'Null contact bypass'); raise exception 'TEST: null contact bypass'; exception when check_violation then null; end;
 begin insert into public.conversations(lead_id,contact_id,channel,thread_key,first_reply_id,last_reply_at) values(l2,contact1,'email','forged',m1,now()); raise exception 'TEST: cross-lead conversation created'; exception when foreign_key_violation or unique_violation then null; end;
 perform public.transition_lead(l1,'qualified','website_interested','Confirmed reply reviewed',null,m1);
 perform public.transition_lead(l1,'website_interested','qualifying','Start sales qualification',null,m1);
 insert into public.projects(lead_id,name,requirements) values(l1,'CORE PROJECT','{"websiteType":"business_website","numberOfPages":1}') returning id into p;
 begin perform public.transition_lead(l1,'qualifying','price_ready','Missing indication',p); raise exception 'TEST: price ready without indication'; exception when raise_exception then if sqlerrm<>'COMPLETE_PRICE_INDICATION_REQUIRED' then raise; end if; end;
 insert into public.price_indications(id,project_id,status,total) values(p::text,p,'ready',895);
 perform public.transition_lead(l1,'qualifying','price_ready','Complete indication reviewed',p);
 perform public.transition_lead(l1,'price_ready','silvijn_approval','Request human review',p);
 begin perform public.transition_lead(l1,'silvijn_approval','price_presented','Not approved yet',p); raise exception 'TEST: price presented without approval'; exception when raise_exception then if sqlerrm<>'APPROVED_SCOPE_AND_PRICE_REQUIRED' then raise; end if; end;
 ap:=public.approve_project_price(p);
 insert into public.outreach_drafts(lead_id,project_id,price_approval_id,purpose,status,sent_at,subject,body) values(l1,p,ap,'price_offer','sent',now()-interval '1 minute','Approved price','Synthetic price communication') returning id into o1;
 perform public.transition_lead(l1,'silvijn_approval','price_presented','Record approved offer presentation',p);
 pm:=public.record_prospect_reply(l1,'email','reply@example.invalid','Acceptance','I accept the quoted amount',received,gen_random_uuid(),o1);
 perform public.transition_lead(l1,'price_presented','price_accepted','Owner records acceptance of offer',p,pm);
 perform public.set_project_payment_plan(p,'split');
 perform public.transition_lead(l1,'price_accepted','payment_pending','Agreed payment plan recorded',p);
 begin perform public.transition_lead(l1,'payment_pending','deposit_paid','No receipt yet',p); raise exception 'TEST: unpaid deposit accepted'; exception when raise_exception then if sqlerrm<>'CONFIRMED_DEPOSIT_REQUIRED' then raise; end if; end;
 perform public.confirm_project_payment(p,447.50,'CORE fixture deposit',gen_random_uuid());
 perform public.transition_lead(l1,'payment_pending','deposit_paid','Reflect existing confirmed deposit',p);
 if (select count(*) from public.payment_events where project_id=p)<>1 then raise exception 'TEST: state transition created a payment'; end if;
 begin perform public.transition_lead(l1,'deposit_paid','in_progress','Incomplete requirements',p); raise exception 'TEST: state bypassed production gate'; exception when raise_exception then if sqlerrm<>'AUTHORIZED_PRODUCTION_REQUIRED' then raise; end if; end;
 -- Automatic production: no new human approval after the authorized receipt.
 update public.projects set requirements_complete=true where id=p;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 execute 'set local role service_role';
 perform public.start_project_production(p);
 if (select status from public.projects where id=p)<>'in_progress' then raise exception 'TEST: autonomous production did not start'; end if;
 if (select lead_status from public.leads where id=l1)<>'in_progress' then raise exception 'TEST: lead lifecycle not aligned with autonomous production'; end if;
 perform public.start_project_production(p);
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',uid,'role','authenticated','email','silvijn@silvijnstudio.com')::text,true);
 perform public.transition_lead(l2,'new','opted_out','Explicit prospect opt-out');
 begin insert into public.outreach_drafts(lead_id,status,sent_at) values(l2,'sent',now()); raise exception 'TEST: opt-out permitted send state'; exception when raise_exception then if sqlerrm<>'OUTREACH_SUPPRESSED' then raise; end if; end;
 begin perform public.transition_lead(l2,'opted_out','analyzing','Attempt to undo opt-out'); raise exception 'TEST: opt-out reopened'; exception when raise_exception then if sqlerrm not like 'INVALID_LEAD_TRANSITION:%' then raise; end if; end;
 if not exists(select 1 from public.audit_events where entity_id=l1::text and action='lead_state_changed' and actor_id=uid) then raise exception 'TEST: lifecycle unaudited'; end if;
 -- Actual authenticated role, not admin bypass, for both rejected and accepted reads/RPCs.
 perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider,'role','authenticated','email','core-outsider@example.invalid')::text,true);
 execute 'set local role authenticated';
 if exists(select 1 from public.conversations) or exists(select 1 from public.lead_contacts) or exists(select 1 from public.inbound_messages) or exists(select 1 from public.conversation_messages) then raise exception 'TEST: outsider read private messages'; end if;
 begin perform public.transition_lead(l1,'in_progress','lost','Unauthorized state change'); raise exception 'TEST: outsider transitioned lead'; exception when insufficient_privilege then null; end;
 begin perform public.record_prospect_reply(l1,'email','x@example.invalid','Forgery','Unauthorized reply',now(),gen_random_uuid()); raise exception 'TEST: outsider created reply'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',uid,'role','authenticated','email','silvijn@silvijnstudio.com')::text,true);
 execute 'set local role authenticated';
 if (select count(*) from public.conversations where lead_id=l1)<>2 then raise exception 'TEST: existing owner cannot read conversations'; end if;
 if (select count(*) from public.conversation_messages where conversation_id=cid)<>5 then raise exception 'TEST: incomplete real timeline or draft leaked'; end if;
 if (select count(*) from public.inbound_messages where id=m1)<>1 then raise exception 'TEST: existing owner cannot read reply'; end if;
 perform public.transition_lead(l1,'in_progress','lost','Owner authorized closure',p);
 begin insert into public.conversations(lead_id,contact_id,channel,thread_key,first_reply_id,last_reply_at) values(l1,contact1,'email','direct',m1,now()); raise exception 'TEST: owner direct conversation insert'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 begin insert into public.inbound_messages(lead_id,contact_id,sender,body,source,reply_confirmed,confirmed_by) values(l1,contact1,'reply@example.invalid','Forged evidence','manual_verified',true,uid); raise exception 'TEST: service forged reply evidence'; exception when insufficient_privilege then null; end;
 if has_table_privilege('anon','public.conversation_messages','SELECT') then raise exception 'TEST: anonymous message view grant'; end if;
 if has_table_privilege('service_role','public.conversations','INSERT') then raise exception 'TEST: service can create an unanswered conversation'; end if;
end $$;
rollback;
select 'PASS: lifecycle edges/gates/stale writes; confirmed reply creation/idempotency; no conversation from unanswered outreach or mocks; lead/contact/thread FKs; opt-out suppression; financial non-bypass; authenticated-role outsider denial and owner access. All fixtures rolled back.' result;
